USE [master]
GO

/****** Object:  Database [EFTester]    Script Date: 07/15/2014 11:10:36 ******/
CREATE DATABASE [EFTester] ON  PRIMARY 
( NAME = N'EFTester', FILENAME = N'c:\Program Files (x86)\Microsoft SQL Server\MSSQL10_50.ZESWITZDEV\MSSQL\DATA\EFTester.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'EFTester_log', FILENAME = N'c:\Program Files (x86)\Microsoft SQL Server\MSSQL10_50.ZESWITZDEV\MSSQL\DATA\EFTester_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [EFTester] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EFTester].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EFTester] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EFTester] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EFTester] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EFTester] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EFTester] SET ARITHABORT OFF 
GO

ALTER DATABASE [EFTester] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EFTester] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [EFTester] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EFTester] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EFTester] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EFTester] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EFTester] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EFTester] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EFTester] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EFTester] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EFTester] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EFTester] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EFTester] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EFTester] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EFTester] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EFTester] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EFTester] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EFTester] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EFTester] SET  READ_WRITE 
GO

ALTER DATABASE [EFTester] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [EFTester] SET  MULTI_USER 
GO

ALTER DATABASE [EFTester] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EFTester] SET DB_CHAINING OFF 
GO


USE [EFTester]
GO
/****** Object:  Table [dbo].[Person]    Script Date: 07/15/2014 11:08:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Person](
	[PersonId] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](50) NULL,
	[LastName] [nvarchar](50) NULL,
	[MiddleName] [nvarchar](50) NULL,
	[StreetAddress1] [nvarchar](50) NULL,
	[StreetAddress2] [nvarchar](50) NULL,
	[City] [nvarchar](20) NULL,
	[State] [nchar](2) NULL,
	[Zip] [nvarchar](10) NULL,
	[Phone] [nvarchar](50) NULL,
	[Email] [nvarchar](250) NULL,
	[CreateDate] [datetime] NULL,
	[CreatedBy] [nvarchar](250) NULL,
	[UpdateDate] [datetime] NULL,
	[UpdateBy] [nvarchar](250) NULL,
 CONSTRAINT [PK_Person] PRIMARY KEY CLUSTERED 
(
	[PersonId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Demo]    Script Date: 07/15/2014 11:08:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Demo](
	[DemoId] [int] IDENTITY(1,1) NOT NULL,
	[ColumnOne] [nvarchar](50) NULL
) ON [PRIMARY]
GO
